import './globals.css'
import { Nunito_Sans } from 'next/font/google'

const nunitosans = Nunito_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Visor Chat',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunitosans.className}>{children}</body>
    </html>
  )
}
